### PR TITLE
Support individual descriptor filenames

### PR DESCRIPTION
**Pull request by j-era**
#161

### CODE REVIEW

**Comment by kalwalt** [comment]
I tested your code, and i have no issues with the examples. But just a note, you modified only the 'standard' ARToolkitNFT.ts class, but that changes should be applied also to the [ARToolkitNFT_simd.ts](https://github.com/webarkit/jsartoolkitNFT/blob/master/src/ARToolkitNFT_simd.ts). Would be awesome also to test the scenario you described in the issue if it possible.

**Comment by j-era** [comment]
Thank you for your feedback! I'll take a look at it.

**Comment by kalwalt** [comment]
I tested your code again and it's fine. In the `ARToolkitNFT_ES6_example.html` i did also this simple test, change this line of code https://github.com/webarkit/jsartoolkitNFT/blob/c9b9551b9e14fa8abb587145b973673ab3617c25/examples/ARToolkitNFT_ES6_example.html#L84
with:

```js
start(['../examples/DataNFT/pinball.fset', '../examples/DataNFT/pinball.fset3', '../examples/DataNFT/pinball.iset'], video, video.videoWidth, video.videoHeight, function() { statsMain.update() }, function() { statsWorker.update() })
```
The example will load the files without issues.
It would be nice also modify the artoolkit.api.js, but for doing this will require to upgrade all the code to ES6. That is possible because newer emscripten versions allow this. For now i think it's enough. I will do by myself in another PR.
I will merge this PR if you have nothing against it.

**Comment by j-era** [comment]
Yeah, sure :) Great!

**Comment by kalwalt** [comment]
@j-era Many thanks for this PR! I will add some infos at the top as reminder, and maybe in the issue.

**Pull request merged**
