### PR TITLE
Add a publishConfig section for GitHub Packages

### PR DESCRIPTION
**Pull request by jcansdale**
This will let `npm publish` know to publish on GitHub Packages.

### CODE REVIEW

**Comment by kalwalt** [comment]
Hi @jcansdale i had this before, but can't publish to github, or if it is published the package is present but can not be installed. At the end i published the package only to npmjs.com without any issue.

**Comment by jcansdale** [comment]
@kalwalt,

> i had this before, but can't publish to github, or if it is published the package is present but can not be installed.

This is strange!

I was able to publish with that addition:
https://github.com/kalwalt/jsartoolkitNFT/compare/master...jcansdale-test:master#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28

...and the following workflow:
https://github.com/kalwalt/jsartoolkitNFT/compare/master...jcansdale-test:master#diff-20d3daa93a9ba0727df6f33b917fb301R29

You can see it is finally able to publish here:
https://github.com/jcansdale-test/jsartoolkitNFT/runs/629366148?check_suite_focus=true#step:5:52

Could you see if a similar workflow works for you?

**Comment by kalwalt** [comment]
thank you @jcansdale ! Yes i tried to setup the workflow but nothing happened... and i tried to install your jsartoolkitnft npm package and i get the same error with mine:

```
npm install @jcansdale-test/jsartoolkitnft@0.7.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jcansdale-test%2fjsartoolkitnft - Not found
npm ERR! 404 
npm ERR! 404  '@jcansdale-test/jsartoolkitnft@0.7.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/walter/.npm/_logs/2020-04-29T12_11_15_182Z-debug.log
```

**Comment by jcansdale** [comment]
@kalwalt,

I've added a publish workflow to this PR:
https://github.com/kalwalt/jsartoolkitNFT/pull/34/files#diff-d12baf69376cf493187158c323efceb4

Any chance you could try merging it so I can see what happens in the GitHub Actions's logs?

**Comment by kalwalt** [comment]
@jcansdale ok i will merge for testing

**Comment by kalwalt** [comment]
Thank you! it seems that now it worked, i would also add the double publication (github and npmjs) as i did in my first try...

**Comment by jcansdale** [comment]
Excellent, I'm glad it sees to be working! 🎉

**Comment by kalwalt** [comment]
Thank you for your support @jcansdale !

**Pull request merged**
